export const CONTENT = {
  orderConfirmationView: {
    heading: "Order confirmation",
    pending: "Confirming your payment…",
    pendingDetail: "This can take a few seconds — please don't close this page.",
    stillProcessingHeading: "This order is still processing.",
    stillProcessingDetail: "We haven't received payment confirmation for this order yet — check back shortly.",
    paidHeading: "Thank you for your order!",
    paidDetail: (orderId: string) => `Order ${orderId} is confirmed.`,
    failedHeading: "We couldn't confirm this payment.",
    failedDetail: "If you were charged, please contact us — otherwise, feel free to try again.",
    orderHeading: (orderId: string) => `Order ${orderId}`,
    backToShop: "Back to shop",
    backToOrders: "Back to your orders",
    tryAgain: "Try checkout again",
    loading: "Loading order…",
    loadError: "We couldn't load this order.",
    notFound: "We couldn't find that order.",
  },
  orderReceipt: {
    items: "Items",
    itemQuantity: (quantity: number) => `Qty ${quantity}`,
    recipient: "Recipient",
    deliveryAddress: "Delivery address",
    deliveryDate: "Delivery date",
    subtotal: "Subtotal",
    tax: "GST",
    total: "Total",
  },
  orderHistoryView: {
    heading: "Your orders",
    loading: "Loading your orders…",
    loadError: "We couldn't load your orders.",
    emptyState: "You haven't placed any orders yet.",
    emptyStateCta: "Browse the shop",
    itemsSummary: (count: number) => `${count} item${count === 1 ? "" : "s"}`,
    viewOrder: "View",
  },
} as const;
