export const CONTENT = {
  filters: {
    heading: "Filters",
    clear: "Clear",
    categoryLabel: "Category",
    occasionLabel: "Occasion",
    colorLabel: "Color",
    seasonLabel: "Season",
    sizeLabel: "Size",
    priceLabel: "Price",
    inStockOnly: "In stock only",
    showResults: "Show results",
  },
  productsView: {
    heading: "Shop",
    loading: "Loading…",
    productsCount: (count: number) => `${count} products`,
    loadError: "We couldn't load products.",
    emptyState: "No products match your filters.",
    clearFilters: "Clear filters",
  },
  productDetailView: {
    relatedHeading: "You might also like",
    loading: "Loading product…",
    notFound: "We couldn't find that product — it may have been removed.",
    backToShop: "Back to shop",
    loadError: "We couldn't load this product.",
    breadcrumbHome: "Home",
    breadcrumbShop: "Shop",
    imageCaption: (index: number, name: string) => `Image ${index} of 4 — ${name}`,
    colorPrefix: "Color: ",
    addToCart: "Add to cart",
    toggleWishlist: "Toggle wishlist",
  },
} as const;
