export const CONTENT = {
  shell: {
    heading: "Admin",
    nav: {
      products: "Products",
    },
  },
  productsView: {
    heading: "Products",
    loading: "Loading…",
    productsCount: (count: number) => `${count} products`,
    loadError: "We couldn't load products.",
    emptyState: "No products yet.",
  },
  productsTable: {
    columns: {
      image: "Image",
      name: "Name",
      sku: "SKU",
      category: "Category",
      price: "Price",
      stock: "Stock",
      status: "Status",
      actions: "",
    },
    inStock: "In stock",
    outOfStock: "Out of stock",
    composite: "Bouquet",
    featured: "Featured",
    addProduct: "Add product",
    edit: "Edit",
  },
  fields: {
    name: "Name",
    slug: "Slug",
    description: "Description",
    sku: "SKU",
    category: "Category",
    colors: "Colors",
    occasions: "Occasions",
    species: "Species",
    size: "Size",
    season: "Season",
    tags: "Tags",
    isFeatured: "Featured",
    priceDollars: "Price (AUD)",
    stockCount: "Stock count",
  },
  validation: {
    slugRequired: "Slug is required.",
    slugInvalid: "Slug can only contain lowercase letters, numbers, and hyphens.",
    nameRequired: "Name is required.",
    descriptionRequired: "Description is required.",
    skuRequired: "SKU is required.",
    categoryRequired: "Select a category.",
    colorsRequired: "Select at least one color.",
    occasionsRequired: "Select at least one occasion.",
    sizeRequired: "Select a size.",
    seasonRequired: "Select a season.",
    priceInvalid: "Enter a valid price greater than $0.",
    stockInvalid: "Enter a stock count of 0 or more.",
  },
  productForm: {
    slugHelp: "Auto-generated from the name — edit before saving if needed.",
    slugLockedHelp: "Slug can't be changed after a product is created.",
    tagsHelp: "Comma-separated.",
    submit: "Save product",
    submitting: "Saving…",
    cancel: "Cancel",
    genericError: "Something went wrong. Please try again.",
    slugTaken: "That slug is already in use — try a different one.",
  },
  newProductView: {
    heading: "Add product",
  },
  editProductView: {
    heading: "Edit product",
    loading: "Loading product…",
    loadError: "We couldn't load this product.",
    compositeUnsupported: "Bouquets can't be edited yet — this is coming in a later phase.",
  },
} as const;
