export const CONTENT = {
  shell: {
    heading: "Admin",
    nav: {
      products: "Products",
      orders: "Orders",
    },
  },
  productsView: {
    heading: "Products",
    loading: "Loading…",
    productsCount: (count: number) => `${count} products`,
    loadError: "We couldn't load products.",
    emptyState: "No products yet.",
  },
  productsTable: {
    columns: {
      image: "Image",
      name: "Name",
      sku: "SKU",
      category: "Category",
      price: "Price",
      stock: "Stock",
      status: "Status",
      actions: "",
    },
    inStock: "In stock",
    outOfStock: "Out of stock",
    composite: "Bouquet",
    featured: "Featured",
    addProduct: "Add product",
    edit: "Edit",
    delete: "Delete",
    deleteConfirmTitle: "Delete product?",
    deleteConfirm: (name: string) => `Delete "${name}"? This can't be undone.`,
    deleteError: "Failed to delete product. Please try again.",
    stockSaveError: "Failed to save stock count.",
    cancel: "Cancel",
  },
  fields: {
    name: "Name",
    slug: "Slug",
    description: "Description",
    sku: "SKU",
    category: "Category",
    isComposite: "This is a bouquet",
    colors: "Colors",
    occasions: "Occasions",
    species: "Species",
    size: "Size",
    season: "Season",
    tags: "Tags",
    isFeatured: "Featured",
    priceDollars: "Price (AUD)",
    stockCount: "Stock count",
  },
  validation: {
    slugRequired: "Slug is required.",
    slugInvalid: "Slug can only contain lowercase letters, numbers, and hyphens.",
    nameRequired: "Name is required.",
    descriptionRequired: "Description is required.",
    skuRequired: "SKU is required.",
    categoryRequired: "Select a category.",
    colorsRequired: "Select at least one color.",
    occasionsRequired: "Select at least one occasion.",
    sizeRequired: "Select a size.",
    seasonRequired: "Select a season.",
    priceInvalid: "Enter a valid price greater than $0.",
    stockInvalid: "Enter a stock count of 0 or more.",
    componentsRequired: "Add at least one component product.",
    componentProductRequired: "Select a product.",
    componentQuantityInvalid: "Enter a quantity of 1 or more.",
  },
  productForm: {
    slugHelp: "Auto-generated from the name — edit before saving if needed.",
    slugLockedHelp: "Slug can't be changed after a product is created.",
    compositeHelp:
      "Bouquets are built from other products — pick their components below. Category will be set to Bouquets, and Species won't apply.",
    compositeLockedHelp: "Can't be changed after a product is created.",
    tagsHelp: "Comma-separated.",
    submit: "Save product",
    submitting: "Saving…",
    cancel: "Cancel",
    genericError: "Something went wrong. Please try again.",
    validationError: "Please fix the highlighted fields and try again.",
    slugTaken: "That slug is already in use — try a different one.",
  },
  productComponentsField: {
    heading: "Components",
    empty: "No components added yet.",
    searchPlaceholder: "Search products to add…",
    searchEmpty: "No matching products.",
    loading: "Loading…",
    remove: "Remove",
    removeConfirmTitle: "Remove component?",
    removeConfirm: (name: string) => `Remove "${name}" from this bouquet?`,
    cancel: "Cancel",
  },
  productImageGallery: {
    heading: "Images",
    empty: "No images yet.",
    uploadLabel: "Upload images",
    uploadHint: "JPEG, PNG, or WEBP, up to 5MB each.",
    uploading: "Uploading…",
    primary: "Primary",
    setPrimary: "Set as primary",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    removeConfirmTitle: "Remove image?",
    removeConfirm: "Remove this image? This can't be undone.",
    uploadError: "Failed to upload image(s). Please try again.",
    uploadTooLarge: (name: string) => `${name} exceeds the 5MB limit.`,
    removeError: "Failed to remove image. Please try again.",
    reorderError: "Failed to update images. Please reload and try again.",
    cancel: "Cancel",
  },
  newProductView: {
    heading: "Add product",
  },
  editProductView: {
    heading: "Edit product",
    loading: "Loading product…",
    loadError: "We couldn't load this product.",
  },
  ordersView: {
    heading: "Orders",
    loading: "Loading…",
    ordersCount: (count: number) => `${count} orders`,
    loadError: "We couldn't load orders.",
    emptyState: "No orders yet.",
    emptyStateFiltered: "No orders match this filter.",
    statusFilterPlaceholder: "All statuses",
  },
  ordersTable: {
    columns: {
      date: "Date",
      customer: "Customer",
      items: "Items",
      total: "Total",
      status: "Status",
      actions: "",
    },
    itemsSummary: (count: number) => `${count} item${count === 1 ? "" : "s"}`,
    updateStatusPlaceholder: "Change status…",
    noActions: "—",
    saveError: "Failed to update order status.",
    cancelOrder: "Cancel order",
    cancelConfirmTitle: "Cancel order?",
    cancelConfirm: (orderId: string) => `Cancel order ${orderId}? This can't be undone.`,
    cancel: "Cancel",
  },
} as const;
