export const CONTENT = {
  checkoutView: {
    heading: "Checkout",
    summaryHeading: "Order summary",
    subtotal: "Subtotal",
    tax: "GST",
    shipping: "Shipping",
    free: "Free",
    total: "Total",
    submit: "Pay with Stripe",
    submitting: "Redirecting to Stripe…",
    emptyCart: "Your cart is empty.",
    backToShop: "Back to shop",
    genericError: "Something went wrong. Please try again.",
    validationError: "Please fix the highlighted fields and try again.",
    outOfStockError: "Some items in your cart are no longer available in the quantity requested. Please review your cart.",
  },
  fields: {
    recipientName: "Recipient name",
    line1: "Address line 1",
    line2: "Address line 2 (optional)",
    suburb: "Suburb",
    state: "State",
    postcode: "Postcode",
    deliveryDate: "Delivery date",
  },
  validation: {
    recipientNameRequired: "Recipient name is required.",
    line1Required: "Address is required.",
    suburbRequired: "Suburb is required.",
    stateRequired: "State is required.",
    postcodeInvalid: "Enter a valid 4-digit postcode.",
    deliveryDateInvalid: "Choose today or a future date.",
    itemsRequired: "Your cart is empty.",
  },
} as const;
